name: Deploy development profile about lotdiz
on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
env:
  DOCKERHUB_USERNAME: ${{ secrets.DEV_DOCKER_ID }}
  DOCKERHUB_PASSWORD: ${{ secrets.DEV_DOCKER_PW }}
  DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }}
jobs:
  deploy:
    needs: test
    environment: develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:product